apiVersion: codefresh.io/v1beta1
kind: Product
metadata:
  name: abbr-worker
spec:
  promotionFlows:
    - name: dev-stg-prod-flow
      gitTriggerSelectors:
        - key: commitMessage
          operator: In
          values:
            - Deploy*
  promotionTemplate:
    versionSource:
      file: values.yaml
      jsonPath: $.worker.image.tag
    promotion:
      Chart.yaml:
        jsonPaths:
          - $.version
          - $.appVersion
      values.yaml:
        jsonPaths:
          - $.worker.image.tag